import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Not Found',
  description: 'Generated by Next.js',
};

export default function NotFound() {
  return (
    <div>
      <h1>Not Found</h1>
    </div>
  );
}
