export const metadata = {
  title: 'about-us',
  description: 'Generated by Next.js',
};

export default function CompanyLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      {children}
      $$$$$
    </div>
  );
}
